menus:
	- 
		name: Home
		link: /
	- 
		name: Category
		link: categories/

# Profile
profile:
	location: Beijing, China
	github: dzyhenry
	#stackoverflow: 
		#title: yumemor
		#href: http://stackoverflow.com/users/5662132/yumemor
	#organization: FECHI/Meituan

#Github
github: 
	username: dzyhenry

#Comments
#duoshuo_username: yumemor # 多说配置
disqus_username: dzyhenry # disqus 配置

# Search 
# google | local
search:
  use: local
